services:
  pmtiles:
    build:
      context: go-pmtiles/.
    volumes:
      - ./source-data:/source-data
      - ./public:/public
  tippecanoe:
    build:
      context: tippecanoe/.
    volumes:
      - ./source-data:/source-data
      - ./public:/public
      - ./tippecanoe/scripts:/scripts
